apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
