db:
  name: flask-db
  replicaCount: 1
  image: vmraduacr.azurecr.io/python-web-app:latest
  containerPort: 5432

service:
  type: ClusterIP  # Adding service type
  port: 5432
  targetPort: 5432

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
