apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: vmraduacr.azurecr.io/python-web-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: DB_URL
              value: "postgresql://postgres:postgres@flask-db-service:5432/postgres"
